const mongoose = require('mongoose');

const groupSchema = new mongoose.Schema({
  groupName: { type: String, required: true, trim: true },
  groupCode: { type: String, required: true, unique: true, trim: true },
  branchName: { type: String, required: true, trim: true },
  organizationName: { type: String, trim: true },
  members: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Member' }],
  leader: { type: mongoose.Schema.Types.ObjectId, ref: 'Member' },
  secretary: { type: mongoose.Schema.Types.ObjectId, ref: 'Member' },
  treasurer: { type: mongoose.Schema.Types.ObjectId, ref: 'Member' },
  loanOfficer: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  meetingDay: { type: String },
  meetingTime: { type: String },
  community: { type: String, trim: true },
  totalGroupCount: { type: Number, default: 0 },
  chairpersonName: { type: String, trim: true },
  chairpersonNumber: { type: String, trim: true },
  recordKeeperName: { type: String, trim: true },
  recordKeeperNumber: { type: String, trim: true },
  boxKeeperName: { type: String, trim: true },
  boxKeeperNumber: { type: String, trim: true },
  moneyCounterOneName: { type: String, trim: true },
  moneyCounterOneNumber: { type: String, trim: true },
  moneyCounterTwoName: { type: String, trim: true },
  moneyCounterTwoNumber: { type: String, trim: true },
  keyholderOneName: { type: String, trim: true },
  keyholderOneNumber: { type: String, trim: true },
  keyholderTwoName: { type: String, trim: true },
  keyholderTwoNumber: { type: String, trim: true },
  keyholderThreeName: { type: String, trim: true },
  keyholderThreeNumber: { type: String, trim: true },
  policeOneName: { type: String, trim: true },
  policeOneNumber: { type: String, trim: true },
  policeTwoName: { type: String, trim: true },
  policeTwoNumber: { type: String, trim: true },

  // Legacy leadership fields retained for backward compatibility.
  presidentName: { type: String, trim: true },
  presidentNumber: { type: String, trim: true },
  securityName: { type: String, trim: true },
  securityNumber: { type: String, trim: true },
  treasurerName: { type: String, trim: true },
  treasurerNumber: { type: String, trim: true },
  police1Name: { type: String, trim: true },
  police1Number: { type: String, trim: true },
  police2Name: { type: String, trim: true },
  police2Number: { type: String, trim: true },
  status: { type: String, enum: ['Active', 'Inactive', 'Pending'], default: 'Pending' },
  groupTotalLoanAmount: { type: Number, default: 0 },
  totalLoans: { type: Number, default: 0 },
  totalExpenses: { type: Number, default: 0 },
  totalFines: { type: Number, default: 0 },
  meetingFineAmount: { type: Number, default: 0 },
  savingsamount: { type: Number, default: 0 },
  socialfundamount: { type: Number, default: 0 },
  totalsocialfund: { type: Number, default: 0 },
  groupsavings: { type: Number, default: 0 },
  totalShares: { type: Number, default: 0 },
  savingsDurationMonths: { type: Number, default: 12 },
  membersavingsshare: { type: Number, default: 0 },
}, { timestamps: true });

module.exports = mongoose.model('Group', groupSchema);
