const mongoose = require('mongoose');

const signatorySchema = new mongoose.Schema({
  name: { type: String, required: true },
  signature: { type: String },
  cellphoneNumber: { type: String },
}, { _id: false });

const loanCollectionSchema = new mongoose.Schema({
  memberName: { type: String, required: true },
  loanAmount: { type: Number, required: true },
  weeklyAmount: { type: Number, required: true },
  fieldCollection: { type: Number, required: true },
  advancePayment: { type: Number, default: 0 },
  fieldBalance: { type: Number, required: true },
  currency: { type: String, required: true, enum: ['USD', 'LRD'] },
  collectionDate: { type: Date, default: Date.now },
  principalPortion: { type: Number },
  interestPortion: { type: Number },
  feesPortion: { type: Number },
  securityDepositContribution: { type: Number },
}, { _id: false });

const loanSchema = new mongoose.Schema({
  group: { type: mongoose.Schema.Types.ObjectId, ref: 'Group', required: true },
  client: { type: mongoose.Schema.Types.ObjectId, ref: 'Member', required: true },
  branchName: { type: String, required: true },
  branchCode: { type: String, required: true },
  meetingTime: { type: String },
  meetingDay: { type: String },
  memberCode: { type: String },
  memberAddress: { type: String },
  guarantorName: { type: String, required: true },
  guarantorRelationship: { type: String, required: true },
  guarantorImage: { type: String },
  loanAmountInWords: { type: String, required: true },
  loanDurationNumber: { type: Number, required: true },
  loanDurationUnit: { type: String, required: true, enum: ['days', 'weeks', 'months', 'years'] },
  purposeOfLoan: { type: String },
  businessType: { type: String },
  disbursementDate: { type: Date },
  endingDate: { type: Date },
  collectionStartDate: { type: Date },
  previousLoanInfo: { type: String },
  memberOccupation: { type: String },
  weeklyInstallment: { type: Number },
  securityDeposit: { type: Number },
  memberAdmissionFee: { type: Number },
  rentingOrOwner: { type: String },
  educationBackground: { type: String, enum: ['high school degree', 'vocational school', 'university degree'] },
  district: { type: String },
  maritalStatus: { type: String, enum: ['Single', 'Married', 'Divorced', 'Widowed'] },
  dependents: { type: Number },
  previousLoanSource: { type: String },
  loanAmount: { type: Number, required: true },
  interestRate: { type: Number, required: true },
  currency: { type: String, required: true, enum: ['USD', 'LRD'], default: 'LRD' },
  status: { type: String, enum: ['pending', 'denied', 'active', 'paid', 'defaulted'], default: 'pending' },
  cancelled: { type: Boolean, default: false },
  cancelledAt: { type: Date },
  cancelledBy: { type: String },
  loanOfficerName: { type: String, required: true },
  totalRealization: { type: Number },
  collections: [loanCollectionSchema],
  guarantorInfo: signatorySchema,
  treasuryInfo: signatorySchema,
  secretaryInfo: signatorySchema,
  groupHeadInfo: signatorySchema,
  loanOfficerInfo: signatorySchema,
  branchManagerInfo: signatorySchema,
}, { timestamps: true });

module.exports = mongoose.model('Loan', loanSchema);
